language: python
python:
  - "2.7"
notifications:
    email:
        recipients:
            - lorena.pantano@gmail.com
        on_success: always
        on_failure: always

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mkdir -p src && cd src \
        && git clone  https://github.com/arq5x/bedtools2 \
        && cd bedtools2  \
        && make \
	&& make install \
	&& P = `pwd` \
        && echo export PATH=${P}/bin:$PATH"

install:
    - "pip install -r requirements.txt --use-mirrors"
    - "python setup.py develop"

script: nosetests

branches:
    only:
        - master
