language: python
python:
  - "2.7"
notifications:
    email:
        recipients:
            - lorena.pantano@gmail.com
        on_failure: always
virtualenv:
    system_site_packages: true
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "echo `pwd`"
  - "echo $PATH"
  - "mkdir -p deps && cd deps \
        && git clone  https://github.com/arq5x/bedtools2 \
        && cd bedtools2  \
        && make \
	&& P=`pwd` \
 	&& export PATH=${P}/bin:$PATH"
  - "cd ../ \
	&& wget http://downloads.sourceforge.net/samtools/samtools/0.1.19/samtools-0.1.19.tar.bz2 \
	&& tar -xjvf samtools-0.1.19.tar.bz2 \
	&& cd samtools-0.1.19 \
	&& make \
	&& P=`pwd` \
	&& export PATH=${P}/bin:$PATH \
	&& cd ../.."
  - "echo $PATH"
  - "pip install conda"
  - "conda create --yes -n seqcluster python ipython pip distribute setuptools nose numpy pysam scipy"
  - "source activate seqcluster "
  - "pip install -U cython"
  - "pip install pybedtools"
  - "pip install colorlog"
  - "conda install --yes -c https://conda.binstar.org/bcbio bcbio-nextgen"
install:
    - "python setup.py install"
script: nosetests
after_script:
    - "cd data/test_cluster"
    - "export PATH=/home/travis/virtualenv/python2.7_with_system_site_packages/bin:$PATH"
    - "seqcluster cluster -m seqs_set.ma -a seqs_set.bam -o res -d"
branches:
    only:
        - master
