sudo: required
dist: trusty
language: python
notifications:
    email:
        recipients:
            - lorena.pantano@gmail.com
        on_failure: always
before_install:
  # - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b -p ~/install
  - export PATH=~/install/bin/:$PATH
  - conda install --yes -c conda-forge -c bioconda  seqcluster bedtools samtools pip nose scipy setuptools -q
  - pip install pytz
  - pip install dateutils
  - python setup.py develop
script: 
  - nosetests
branches:
    only:
        - master
        - devel
