sudo: required
dist: trusty
language: python
python:
    - "3.6"
    - "2.7"
notifications:
  email:
    recipients:
    - lorena.pantano@gmail.com
    on_failure: always
before_install:
- echo $TRAVIS_PYTHON_VERSION
- miniconda="Miniconda3-latest-Linux-x86_64.sh"
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]] ; then miniconda="Miniconda2-latest-Linux-x86_64.sh"; fi
- wget -O miniconda.sh http://repo.continuum.io/miniconda/${miniconda}
- bash miniconda.sh -b -p ~/install
- export PATH=~/install/bin/:$PATH
- conda install --yes -c conda-forge -c bioconda openjdk pysam bedtools samtools mirtop -q
- pip install -r requirements.txt
# scipy pandas pybedtools progressbar pip biopython nose scipy setuptools pyyaml -q
- python setup.py install
script:
- nosetests
branches:
  only:
  - master
  - devel
deploy:
  provider: pypi
  user: lpantano
  skip_existing: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|devel$
    distributions: sdist bdist_wheel
    repo: lpantano/seqcluster
  password:
    secure: CcHxZZOvi2OeXgVhHZbF0cGZd3nuTJ9mZ2QO7LmqU/Ri7s0nsmn3WL02F7aG9sJD+yliR0S3CN6QR430CVwnkHwefDSQrgZ6yMzdViWzWnaycu+xOscIaRtczvkAvg3Ye4yljvbk+7ZohowVl+3GVP+fKmeds+7ET8Ul9JMbt+Q=
