sudo: required
dist: trusty
language: python
notifications:
  email:
    recipients:
    - lorena.pantano@gmail.com
    on_failure: always
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
- bash Miniconda-latest-Linux-x86_64.sh -b -p ~/install
- export PATH=~/install/bin/:$PATH
- conda install --yes -c conda-forge -c bioconda  seqcluster bedtools samtools pip
  nose scipy setuptools -q
- pip install pytz
- pip install dateutils
- python setup.py develop
script:
- nosetests
branches:
  only:
  - master
  - devel
deploy:
  provider: pypi
  user: lpantano
  skip_existing: true
  on:
    distributions: sdist bdist_wheel
    repo: lpantano/seqcluster
  password:
    secure: CcHxZZOvi2OeXgVhHZbF0cGZd3nuTJ9mZ2QO7LmqU/Ri7s0nsmn3WL02F7aG9sJD+yliR0S3CN6QR430CVwnkHwefDSQrgZ6yMzdViWzWnaycu+xOscIaRtczvkAvg3Ye4yljvbk+7ZohowVl+3GVP+fKmeds+7ET8Ul9JMbt+Q=
