language: python
python:
  - "2.7"
notifications:
    email:
        recipients:
            - lorena.pantano@gmail.com
        on_success: always
        on_failure: always

before_install:
  - "mkdir -p src && cd src \
        && git clone  https://github.com/arq5x/bedtools2 \
        && cd bedtools2  \
        && make \
	&& P = `pwd` \
        && export PATH=${P}/bin:$PATH"
  - "cd \
	&& cd src \
	&& wget http://sourceforge.net/settings/mirror_choices?projectname=samtools\&filename=samtools/0.1.19/samtools-0.1.19.tar.bz2 \
	&& cd samtools \
	&& make \
	&& P = `pwd` \
        && export PATH=${P}/bin:$PATH"
  - "echo $PATH"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "python setup.py develop"

script: nosetests

branches:
    only:
        - master
